# -*- coding: utf-8 -*-
"""Sentimental_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17N8ggE0PcqRSXjXj40koj2nr1a66Qdx0
"""

!pip install openai

import openai

# using the openai api key
openai.api_key = "" #key is generated on playground everyone use's their own key.

import openai

openai.api_key = ""

def sentiment_analysis(text):
  messages = [
      {"role": "system", "content": """ you are trained analyse and detect the sentiment of given text.
      if you're unsure of an answer, you can say "not sure" and recommend users to review manually."""},
      {"role": "user", "content": f"""Analyze the following text and determine if the sentiment is: positive or negative.
      Return answer in single word as either positive or negative: {text}"""}
  ]

  response = openai.chat.completions.create(model = "gpt-3.5-turbo",
                                          messages = messages,
                                          max_token = 1,
                                          n = 1,
                                          temperature = 0)

  response_text = response.choices[0].message.content.strip().lower()
  return response_text

# calling the function
input = 'I hate fast food'
response = sentiment_analysis(input)
print(input,': The sentiment is', response)

